name = "unsafekv"
type = "javascript"
route = ''
zone_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = true
compatibility_date = "2021-10-26"

kv_namespaces = [
    { binding = "UnsafeKV", id = "7e41028ad7ec4bc0abca1e15c813b568" }
]

[build]
command = "yarn install && yarn run build"

[build.upload]
format = "service-worker"
